# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


# Triggers can be based on specific branches, tags, or even schedules.
trigger:
  branches:
    include:
      - master
      # - feature/*

# pr:
#   branches:
#     include:
#     - master
#     - feature*

# variables:
#   - group: domo-api-variables
#   - name: BuildConfiguration
#     value: "Release"

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        # Job configuration goes here
        steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
          - script: echo System.DefaultWorkingDirectory
          
          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script'

          - task: CmdLine@2
            inputs:
              script: |
                echo  "$(System.DefaultWorkingDirectory)"

          - task: CmdLine@2
            inputs:
              script: |
                echo "Structure of work folder of this pipeline:"
                tree $(Agent.WorkFolder)/1
      
                echo "Build.ArtifactStagingDirectory:" 
                echo "$(Build.ArtifactStagingDirectory)"
      
                echo "Build.BinariesDirectory:" 
                echo "$(Build.BinariesDirectory)"
      
                echo "Build.SourcesDirectory:"
                echo "$(Build.SourcesDirectory)"

  - stage: Test
    jobs:
      - job: TestJob
        # Job configuration goes here

  - stage: Infra
    jobs:
      - job: CrateStorage
        # Job configuration goes here
        steps: 
        # - task: AzureCLI@2
        #   displayName: Create Storage 
        #   inputs:
        #     azureSubscription: serviceconnection
        #     scriptType: pscore
        #     scriptLocation: inlineScript
        #     inlineScript: az storage account create -n "stg09234504" -g "example-rg" -l "UK South" --sku Standard_LRS

        - task: AzureCLI@2
          displayName: Create Storage
          inputs:
            azureSubscription: serviceconnection
            scriptType: pscore
            scriptLocation: scriptPath
            inlineScript: $(System.DefaultWorkingDirectory)/CLI/StorageAccount.azcli

        # - task: AzureCLI@2
        #   displayName: 'Deploy AKS'
        #   inputs:
        #     azureSubscription: $(AzureResourceManagerConnection)
        #     scriptType: bash
        #     scriptLocation: inlineScript
        #     addSpnToEnvironment: true
        #     inlineScript: |
        #       #!/bin/bash     
    
        #       # $AKS_RG = "aks-rg"  
        #       # $AKS_CLUSTER = "aks-cluster"   
        #       # $AKS_LOCATION = "southindia"
    
        #       az group create -l southindia -n aks-rg
        #       az aks create -g aks-rg -n aks-cluster --enable-managed-identity --node-count 1 --generate-ssh-keys
