# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureCLI@2
  displayName: Create Storage 
  inputs:
    azureSubscription: serviceconnection
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: az storage account create -n "stg09234504" -g "example-rg" -l "UK South" --sku Standard_LRS

- task: AzureCLI@2
  displayName: Create Storage
  inputs:
    azureSubscription: serviceconnection
    scriptType: pscore
    scriptLocation: scriptPath
    inlineScript: $(Pipeline.Workspace)/CLI/StorageAccount.azcli